FROM python:3.9-slim-buster

WORKDIR /app

# Some utilities for installing Chrome/Chromedriver
RUN apt-get update && apt-get install -y \
    wget \
    unzip

# Set up Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# Install curl
RUN apt-get update && apt-get install -y curl

# Set up Chromedriver
RUN LATEST=`curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE` &&\
    echo "Installing chromium webdriver version ${LATEST}" &&\
    wget -q https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip -O /tmp/chromedriver.zip &&\
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ &&\
    rm /tmp/chromedriver.zip

# Copy the requirements file from the tests directory
COPY ./requirements.txt ./requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the test files from the tests directory
COPY . .

# Run the tests
CMD ["pytest", "--url=http://nginx:80", "./meetup_tests.py"]
